### ISSUE TITLE
Funny Apps

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#101]
# Tasks

## Add the Page

- [x] Add `Funny Apps` page at the bottom of `Team sinProject` category
- [x] Description: `Here are some of our favorite apps and games.`

## `Joke Apps` section

- [x] - [Cool-Retro-Term](https://github.com/Swordfish90/cool-retro-term/releases)
- [x] - [unimatrix](https://github.com/will8211/unimatrix)
- [x] - [sl](https://github.com/mtoyoda/sl)
  - [x] To install: `brew install sl`
- [x] - [hollywood](https://github.com/dustinkirkland/hollywood)
  - [x] To install:
    - [x] 1. `brew brew tap real-aazam/homebrew-aazam`
    - [x] 1. `brew install hollywood`

## `Web' section

- [x] - [GEEKTyper.com - Cyberpunk](https://geektyper.com/cyberpunk/)
- [x] - [Hacker Typer](https://hackertyper.net/)

## `Games` section

- [x] - [Hacknet](https://store.steampowered.com/app/365450/Hacknet/)

Estimated time: 20 min

参考
https://www.aura-office.co.jp/blog/omoshiro_web/

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by gottu91-code** [comment]
コード(brew install slなど)は以下のページのようにコードセクションで記載
[brew install --cask warp](https://sinpro.dev/docs/customize-zsh)
