### ISSUE TITLE
Fix TypeError on the top page

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#107]
# Tasks

- [x] Fix TypeError on the top page

Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
    at respond (service-worker.js:53:11)

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by gottu91-code** [comment]
◇エラーが出ていた原因
Service Workerで許可されていないリクエストURL([chrome-extension://](chrome-extension://xn--n9j/) を含むURL)を処理しようとしていたため。

下記のようにchrome拡張機能から発生するリクエストはService Workerで許可されていないためエラーが出る。
chrome-extension://cofdbpoegempjloogbagkncekinflcnj/fonts/OpenSans_VariableFont_wdth_wght.ttf

下記のようなリクエストURLは問題なく処理できる。
http://localhost:5173/src/routes/+layout.svelte
https://sinpro.dev/docs/concurrency

◇参考になった記事
[Service Worker TypeError when opening Chrome extension](https://stackoverflow.com/questions/49157622/service-worker-typeerror-when-opening-chrome-extension)
[Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported #1](https://github.com/iamshaunjp/pwa-tutorial/issues/1)
[ServiceWorkerをサクッと導入してみた](https://tech.012grp.co.jp/entry/2021/09/24/121855)
[Service Workerについて調べたのでメモ](https://zenn.dev/s_takashi/articles/b01980461f3b21)

◇備考
現環境でもchrome拡張機能をすべてオフにすると、エラーが非表示となります。
