### ISSUE TITLE
Look up if husky can stop when there are warnings

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#122]
# Tasks

- [x] Look up if husky can stop when there are warnings

Estimated time: 20 min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by Acha0203** [comment]
タスク内容に「Look up if husky can stop when there are **warnings**」とありますが、eslint は warnings (警告) が出ても非ゼロの終了コードを返さないため、husky がコミットを停止することはないそうです。テスト用のブランチを切って試してみましたが、やはりコミットは停止しませんでした。

ただし、errors が出た際は husky がコミットを停止するはずですので、それについては、たとえばコードに console.log などを追加することで検証できます。正しいタスク内容は「Look up if husky can stop when there are **warnings**」ではなく「Look up if husky can stop when there are **errors**」であると解釈してよろしいでしょうか。

あるいは、.husky/pre-commit に
```
echo "これはテスト警告です"
exit 1
```
と追加して人工的に非ゼロの終了コードを返すように設定し、husky が停止するかどうか調べることもできます。

どちらのやり方を想定されていますでしょうか？

**Comment by sinproject-iwasaki** [comment]
> タスク内容に「Look up if husky can stop when there are **warnings**」とありますが、eslint は warnings (警告) が出ても非ゼロの終了コードを返さないため、husky がコミットを停止することはないそうです。テスト用のブランチを切って試してみましたが、やはりコミットは停止しませんでした。

ご確認ありがとうございます。

> ただし、errors が出た際は husky がコミットを停止するはずですので、それについては、たとえばコードに console.log などを追加することで検証できます。正しいタスク内容は「Look up if husky can stop when there are **warnings**」ではなく「Look up if husky can stop when there are **errors**」であると解釈してよろしいでしょうか。

いいえ。エラーが出るときに泊まることは確認できていますので、今回は、lint などでの警告のときに泊まるかを確認したかったものです。

今回は、「eslint は warnings (警告) が出ても非ゼロの終了コードを返さないため、husky がコミットを停止することはない」という検証ができたようですので、これで検証完了で大丈夫です。

前後してしまいましたが、この検証に対して報酬を差し上げたいと思いますので、希望報酬をDMにてご連絡くださいませ。

**Comment by Acha0203** [comment]
ご返信ありがとうございます。承知いたしました。
