### ISSUE TITLE
導入実績を表示する

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#140]
# Tasks

- [ ] 導入実績表示があるサイトを確認する。
- [ ] 導入実績を表示する。

[サブスクペイ](https://www.robotpayment.co.jp/lan/payment/2104/)

導入実績
大手から中小まで14,000社以上の導入実績
年間900億円以上の取引に活用されています。

[NP架け払い](https://np-kakebarai.com/lp/atobarai_yago_1a/)
スクロール表示

https://svelte.dev/
loved by developers
contributors
donors

https://tailwindcss.com/

https://eslint.org/
Sponsored by fantastic people
We receive $133,176.00 / year in donations from 166 sponsors.

https://prettier.io/
Used By People You Rely On

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
