### ISSUE TITLE
Code Analysis

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#141]
# Tasks

- [ ] githubコードスキャン
- [ ] code climate
- [ ] テストカバレッジ

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sinproject-iwasaki** [comment]
[Code Maintainability を測る](https://zenn.dev/hrntsm/books/grasshopper-ci/viewer/code-maintenace)
プルリク時に動くようにする

**Comment by sinproject-iwasaki** [comment]
[GitHubでTypeScriptのプロダクトを作るときに便利な連携サービス](https://qiita.com/kotauchisunsun/items/95a8f22c59bc941bee9e)

**Comment by sinproject-iwasaki** [comment]
SideCI、Codacy, Scrutinizer, Hound

**Comment by sinproject-iwasaki** [comment]
[開発効率を上げる！コードレビュー自動化サービス4選を使ってみた【SideCI・Codacy・Hound・Scrutinizer】](https://paiza.hatenablog.com/entry/2018/03/05/automated_code_review_services)

**Comment by sinproject-iwasaki** [comment]
[攻めのサーバーサイド戦略！技術トレンドの実態に迫る](https://flxy.jp/media/article/16218)

**Comment by sinproject-iwasaki** [comment]
[Windows アプリ開発で利用している Web サービス](https://clown.cube-soft.jp/entry/20180511/service-for-windows-developer)

**Comment by sinproject-iwasaki** [comment]
https://codeclimate.com/github/sinProject-Inc/sinpro-dev/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication

**Comment by sinproject-iwasaki** [comment]
[Cognitive Complexityを400以上減らすまでに何をしたか 〜 コード品質改善の具体的なプラクティス](https://techblog.yahoo.co.jp/entry/2022082430334618/)
