### ISSUE TITLE
Add items to Equipment and Supplies

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#151]
# Tasks

- [x] Add an item to the top of Electronics Cables and Chargers
- [x] Add an item to the bottom of Anker 747 Charger

```
<a href="https://www.amazon.co.jp/MOTTERU-%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB%E3%83%90%E3%83%83%E3%83%86%E3%83%AA%E3%83%BC-20000mAh-USB-C%E5%85%A5%E5%87%BA%E5%8A%9B-MOT-MB20001-GY/dp/B09FDFRMMV?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&crid=ABXEV4UL8PI&keywords=20000mah%2BMOTTERU&qid=1691012963&s=dmusic&sprefix=20000mah%2Bmotter%2Cdigital-music%2C157&sr=1-1&th=1&linkCode=li3&tag=claltc-22&linkId=f1288655cbac85f26dd395126ba2307a&language=ja_JP&ref_=as_li_ss_il" target="_blank"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B09FDFRMMV&Format=_SL250_&ID=AsinImage&MarketPlace=JP&ServiceVersion=20070822&WS=1&tag=claltc-22&language=ja_JP" ></a><img src="https://ir-jp.amazon-adsystem.com/e/ir?t=claltc-22&language=ja_JP&l=li3&o=9&a=B09FDFRMMV" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
```

```
<a href="https://www.amazon.co.jp/gp/product/B08R872PF7?ie=UTF8&psc=1&linkCode=li3&tag=claltc-22&linkId=8a30ed3698d37099b1697d4367c39f7b&language=ja_JP&ref_=as_li_ss_il" target="_blank"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B08R872PF7&Format=_SL250_&ID=AsinImage&MarketPlace=JP&ServiceVersion=20070822&WS=1&tag=claltc-22&language=ja_JP" ></a><img src="https://ir-jp.amazon-adsystem.com/e/ir?t=claltc-22&language=ja_JP&l=li3&o=9&a=B08R872PF7" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
```

想定時間: 5分

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
