### ISSUE TITLE
Add the highlighting extensions

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#164]
# Tasks

2 extensions 

- [x] Add the `Indented Block Highlighting` extension to recommended Extension settings
- [x] Add the `Indented Block Highlighting` extension to Recommended Extensions page
- [x] Add the `Indenticator` extension to recommended Extension settings
- [x] Add the `Indenticator` extension to Recommended Extensions page
- [x] https://marketplace.visualstudio.com/items?itemName=byi8220.indented-block-highlighting
- [x] https://marketplace.visualstudio.com/items?itemName=SirTori.indenticator

1000pt

Estimated Time: 10min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
