### ISSUE TITLE
Add VSCode Extensions

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#183]
# Tasks

https://sinpro.dev/docs/vscode-workspace-extensions

## SonarLint

- [x] extensions.json に追加する
- [x] `Code Quality` セクションの一番上に `SonarLint` を追加する

## Add the Markdown All in One]

- [x] extensions.json に追加する
- [x] CodeQuality の下に「Markdown」セクションを追加する
- [x] 拡張機能「Markdown All in One」を追加する

Estimated Time: 10min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
