### ISSUE TITLE
Change facebook link

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#226]
# Tasks

- [x] リンク形式（リンク文字列）をYahooニュースと同じ形式にする
- [x] ngrok で、モバイル端末で Facebook アプリが起動するかを確認する (iOSでは起動しない？Androidは？）
- [x] twitter.com も x.com に変更して、X のスマホアプリが起動するかを確認する

参考：https://news.yahoo.co.jp/ のニュースページを確認する

Estimated Time: 10min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by Acha0203** [comment]
試しに自分のスマホ（iPhone SE 第3世代/iOS 16.6）でYahoo ニュースのFacebookリンクをタップしてみましたが、Facebookアプリが起動しません。調べたところ、Facebookのリンクは環境によって挙動が異なるようです。

どの環境でもFacebookアプリが起動するようにするには「fb:~」というURLスキームを使用する必要があリます。ただし、ユーザーのデバイスやブラウザの種類、Facebookアプリのバージョンによっては期待通りの動作をしない場合があるため、実際のデバイスでのテストを繰り返し行い、最も一般的なシナリオに対応するような実装を目指す必要があります。

**Comment by Acha0203** [comment]
Yahoo ニュースのFacebookリンクですが、Android端末の場合はFacebookアプリが起動することを確認いたしました。

**Comment by Acha0203** [comment]
mainブランチのコードに対してPlaywright Testを実行したところ、テストが通りませんでした。
エラーの内容:
access a page: Test timeout of 10000ms exceeded.
close search modale with keyboard shortcut:
Test finished within timeout of 10000ms, but tearing down "context" ran out of time.
Please allow more time for the test, since teardown is attributed towards the test timeout budget.
open search modale with navbar button: Test timeout of 10000ms exceeded.
copy code: Test timeout of 10000ms exceeded while running "beforeEach" hook.

現時点でエラーの原因は特定できておりませんが、タイムアウト時間を延長することでパスできました。PR作成の際にタイムアウト時間を延長しても差し支えないでしょうか？

**Comment by Acha0203** [comment]
ngrok でモバイル端末で Facebook アプリが起動するかを確認しましたが、iOSとAndroidのどちらもFacebook アプリは起動せず、ブラウザが起動しました。
