### ISSUE TITLE
Update npm packages

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#246]
# Tasks

- [x] Update npm packages
- [x] npm run dev で表示を確認し、エラーが出ないこと
- [x] npm run build && node build で表示を確認し、エラーが出ないこと

```bash
cd <project_root>
ncu
ncu -u
npm i
```

Estimated time: 5min

参考：https://sinpro.dev/docs/npm-check-updates#usage

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by Acha0203** [comment]
Updateとは無関係だと思いますが、commit時に次のエラーが発生しました。

/sinpro-dev/src/lib/components/navbar.svelte
  29:29  error  Replace `flex·items-center·gap-2·text-[22px]·no-underline·titl` with `title·flex·items-center·gap-2·text-[22px]·no-underlin`  prettier/prettier

/sinpro-dev/src/routes/docs/[slug]/+page.svelte
  104:15  error  Replace `flex·justify-end·gap-3·my-8` with `my-8·flex·justify-end·gap-3`  prettier/prettier
  
  上記メッセージのとおりに修正して構いませんでしょうか？

**Comment by Acha0203** [comment]
PR 作成時に次のようなエラーが発生しました。

```
/Users/ikedaatsuko/web-projects/sinProject-Inc/sinpro-dev/src/lib/components/social_meta_tags.svelte:29:3
Error: Type '{ url: string; type: string; title: string; description: string; images: { url: string; alt: string; }[]; site_name: string; }' is not assignable to type 'OpenGraph'.
  Object literal may only specify known properties, but 'site_name' does not exist in type 'OpenGraph'. Did you mean to write 'siteName'? (ts)
                images: [{ url: image_url, alt: image_alt }],
                site_name,
        }}
```
「site_name」を「siteName」に修正する必要があるようですが、修正してしまって構いませんでしょうか？
