### ISSUE TITLE
Replace 'px-2·overflow-visible' with 'overflow-visible·px-2'

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/sinpro-dev#260]
# Tasks

- [ ] Replace `px-2·overflow-visible` with `overflow-visible·px-2`
Target File: `/src/lib/components/icons/right_arrow_icon.svelte`
Errors currently appearing: `Error: 1:32  error  Replace 'px-2·overflow-visible' with 'overflow-visible·px-2'  prettier/prettier`

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by gottu91-code** [comment]
https://github.com/sinProject-Inc/sinpro-dev/pull/259
こちらのPRで岩崎さんが対応済み。
