### ISSUE TITLE
Update PR Template

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#268]
# Tasks

file: ./github/pull_request_template.md

- [ ] Insert the following text after `Make sure CI completes successfully

`Fix the issues pointed out by AI`

Estimated TIme: 3min

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by Acha0203** [comment]
このタスクの内容についてですが、

pull_request_templete.md を ChatGPT に見せて、指摘された部分を修正する

という認識で合っていますでしょうか？
