### ISSUE TITLE
Move the create_git_branch.ts to scripts directory

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#293]
# Tasks

- [x] Create `scripts` directory on project root directory
- [x] Move the create_git_branch.ts to `scripts` directory
- [x] Modify the package.json command

Estimated Time: 10min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by Acha0203** [comment]
scripts ディレクトリはプロジェクトのルートに新しく作成するのでしょうか？

**Comment by sinproject-iwasaki** [comment]
@Acha0203 

はい。プロジェクトのルートに scripts ディレクトリを作成して、そこに移動してもらいたいです。Issue の内容も少し更新いたしました。
以降、sinpro-dev や talk のご質問は 後藤さん宛で、CCとして岩崎もメンションを付けてご連絡いただけましたら幸いです。よろしくお願いいたします。

**Comment by Acha0203** [comment]
ご回答ありがとうございます。承知しました。

**Comment by Acha0203** [comment]
create_git_branch.ts を移動すると、同ファイル内に「プロパティ 'replaceAll' が型 'string' に存在しません。ターゲット ライブラリを変更する必要がありますか? 'lib' コンパイラ オプションを 'es2021' 以降に変更してみてください。」というエラーが出るため、.svelte-kit/tsconfig.json の include オプションに 次のように追記する必要がありますが、差し支えないでしょうか？

```
"include": [
    ...
    "../scripts/**/*.ts"
]
```

**Comment by gottu91-code** [comment]
@Acha0203 

> .svelte-kit/tsconfig.json の include オプションに 次のように追記する必要がありますが、差し支えないでしょうか？

.svelte-kitディレクトリはSvelteKitが自動的に生成するものなのでこの中を触ることはありません。
(.svelte-kitディレクトリを削除してnpm run devすると再生成されるのが確認できます)

今回のエラーの原因は、「tsconfigがルートディレクトリのscriptsディレクトリを認識していない」ことでした。
tsconfig.jsonに「"include": ["scripts/**/*"]」を追加すると今回のエラーが消えるかと思います。

しかしさきほど岩崎さんと話したところ、tsconfig.jsonをあまり変更したくない、という方針があるようです。

なので、tsconfig.jsonは触らずに、scriptsディレクトリを作成するのはsrc直下でお願いいたします。
.svelte-kit/tsconfig.json でsrcディレクトリは認識されているのでエラーが出ないはずです。

**Comment by Acha0203** [comment]
@gottu91-code 

ご回答ありがとうございます。承知しました。
