### ISSUE TITLE
Disable Squash and Rebase Operations

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#294]
# Tasks

- [x] Disable Squash and Rebase Operations

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by sinproject-iwasaki** [comment]
Git にて Squash と rebase のデメリットを教えて

## GPT-4

```md
Gitでの`Squash`と`Rebase`操作は非常に便利ですが、慎重に使用しないと問題を引き起こす可能性があります。

### Squashのデメリット

1. **履歴の喪失**: Squashは複数のコミットを一つにまとめるので、それぞれのコミットで行われた個別の変更の履歴が失われます。これは、後で問題の調査や`git blame`を使用したときに不便です。
  
2. **コンフリクト**: Squashする前後で、他のブランチが元のコミットに依存している場合、コンフリクトが生じる可能性が高まります。
  
3. **可読性**: 一つのコミットに複数の変更がまとめられると、そのコミットが何をしているのか理解しづらくなる場合があります。

### Rebaseのデメリット

1. **複雑な履歴**: Rebaseを行うと、新しいコミットIDが生成され、これが分かりにくい履歴を作り出す場合があります。特に、`git push --force`が必要な場合、リモートの履歴が非常に読みにくくなります。
  
2. **共有されたコミットの危険性**: 他の人が既にプッシュしたコミットをRebaseすると、整合性のない履歴が作成されます。これは特に共有されているブランチで起こり、混乱やデータの喪失を引き起こす可能性があります。
  
3. **コンフリクトの複雑性**: Rebaseは各コミットを一つずつ適用するため、複数のコンフリクトが生じるとその解決が複雑になる場合があります。

どちらの操作も非常に強力ですが、正確にどう働くのか、そしてそれぞれが持つリスクを理解していないと、問題を引き起こす可能性があります。
```

## Bing Chat

```md
GitのSquashとRebaseにはそれぞれ以下のようなデメリットがあります：

**[Squashのデメリット](about:blank#)**³⁴⁵：
[1](https://www.w3schools.blog/git-squash). **コミット履歴の喪失**：Squashは複数のコミットを1つにまとめるため、コミット履歴が失われ、コードの変更履歴を理解するのが難しくなります。
[2](https://felixmoessbauer.com/blog-reader/why-git-squash-merges-are-bad.html). **トレーサビリティの低下**：複数のコミットを1つのコミットにまとめることで、Git履歴の粒度が低下し、特定の変更を追跡するのが難しくなります。
[3](https://dev.to/wesen/squash-commits-considered-harmful-ob1). **情報の喪失**：Squashは情報を失うだけでなく、履歴を綺麗にするためだけに存在します。これは一部のGitクライアントが綺麗なコミットグラフを表示し、中間ファイル状態を保存しないことで少しのスペースを節約することを助けます。

**[Rebaseのデメリット](https://qiita.com/hinako_n/items/2e81141ce74b3b7d1d56)**⁶⁷⁸⁹[^10^]：
1. **マージコンフリクト**：長期間にわたるブランチがmasterブランチから大きく逸脱している場合、Rebaseするとマージコンフリクトが頻繁に発生する可能性があります。
2. **コミットの喪失**：Rebaseは過去のコミットを上書きする可能性があります。
3. **コミット情報の欠如**：Rebaseは各コミットでコンフリクト解消が必要であり、これは混乱を招く可能性があります。特に、長いチェーンのコミットをRebase中にコンフリクトが発生した場合、それを解決することは困難であり、潜在的なエラー源となります。
[4](https://qiita.com/hinako_n/items/2e81141ce74b3b7d1d56). **テストの無効化**：Rebaseはテストを無効化する可能性があります。これは新たなエラーが歴史を書き換える際に導入され、それらが最初に歴史を書いた際に導入された本当のバグを隠す可能性があります。特に、これはGit bisect（Gitツールボックスで最も強力なデバッグツール）を使用することを難しくします。

これらは一般的なガイドラインであり、具体的な使用方法はあなたのプロジェクトやチームの要件によります。必要に応じて適切な手法を選択してください。

ソース: Bing との会話 9/18/2023
(1) Git Squash - W3schools. https://www.w3schools.blog/git-squash.
(2) Why git squash merges are bad - Felix Mößbauer - Software .... https://felixmoessbauer.com/blog-reader/why-git-squash-merges-are-bad.html.
(3) ⛔ Squash commits considered harmful ⛔ - DEV Community. https://dev.to/wesen/squash-commits-considered-harmful-ob1.
(4) 【Git】リベースの使い方と注意点 - Qiita. https://qiita.com/hinako_n/items/2e81141ce74b3b7d1d[5](https://medium.com/@fredrikmorken/why-you-should-stop-using-git-rebase-5552bee4fed1)[6](https://phoenixnap.com/kb/git-rebase-vs-merge).
(5) Why you should stop using Git rebase | by Fredrik V. Mørken .... https://medium.com/@fredrikmorken/why-you-should-stop-using-git-rebase-5552bee4fed1.
(6) Git Rebase vs. Git Merge: What's the Difference? - phoenixNAP. https://phoenixnap.com/kb/git-rebase-vs-merge.
([7](https://stackoverflow.com/questions/10000624/what-are-the-downsides-to-rebasing-topic-branches-instead-of-merging)) git - What are the downsides to rebasing topic branches .... https://stackoverflow.com/questions/10000624/what-are-the-downsides-to-rebasing-topic-branches-instead-of-merging.
([8](https://coderefinery.github.io/git-branch-design/01-rebase/)) CodeRefinery - GitHub Pages. https://coderefinery.github.io/git-branch-design/01-rebase/.
(9) Git Squashで複数のコミットをひとつにまとめる方法｜実例付. https://itc.tokyo/git/git-squash/.
(10) 他人のコミットをgit merge --squashするべきでないのではという話 .... https://qiita.com/pshiko/items/1e9acd114b7e85884866.
(11) undefined. http://d.hatena.ne.jp/sinsoku/20111025/1319497900.
(12) undefined. https://help.github.com/articles/creating-a-commit-with-multiple-authors/.
```
