### ISSUE TITLE
Create new Issue Template: Update Each Repository

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#295]
# Tasks

- [ ] Create new Issue Template: Update Each Repository

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by iamsin** [comment]
テンプレートは作らずに、[プロダクト対応表](https://docs.google.com/spreadsheets/d/1REZlXMy67XGSBubbESUxfwXGV54So5r7FYwZZDd69bI/edit#gid=0)を作ることに変更した。
