### ISSUE TITLE
Add Merge pull request section to GitHub Pull Request Page

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/sinpro-dev#296]
# Tasks

- [ ] GitHub Pull Request ページの一番下に `Merge pull request` セクションを追加
- [ ]  下記を適切な英語にして追加する
```
Select Create a merge commit
Don’t select Squash and merge or Rebase and merge
もしこれらを使いたいなら、使う前に良さを教えてください。方針を検討します。
```

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Share your screen on Discord
- [ ] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
