### ISSUE TITLE
Check VSCode Workspace Extensions page

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/sinpro-dev#302]
# Tasks

- [x] Make the VSCode Workspace Extensions page and extensions.json match.

Estimated Time: 20min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks

**Comment by gottu91-code** [comment]
extension.json の内容は [VSCode Workspace Extensions](https://sinpro.dev/docs/vscode-workspace-extensions) ページに全て反映されていました。
