### ISSUE TITLE
Update the test code referring to the latest skelton of SvelteKit

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#314]
# Tasks

[Add checks and tests GitHub Actions #9](https://github.com/sinProject-Inc/post-master/issues/9)

- [x] Update action.yml
- [x] Update ci.yml
- [x] Update pre-push
- [x] Update 3 doc pages
- [x] Update package.json

Estimated Time: XXmin

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by sinproject-iwasaki** [comment]
[CI/Vitest Test, Playwright Test]   ❗  ::error::Unable to get ACTIONS_RUNTIME_TOKEN env variable
[CI/Vitest Test, Playwright Test]   ❌  Failure - Main actions/upload-artifact@v3

artifacts path を指定して実行する。

mkdir -p /tmp/act-artifacts
act -j tests --artifact-server-path /tmp/act-artifacts
