### ISSUE TITLE
Update Release Tempalte

### ISSUE THREAD

**Issue by gottu91-code** [sinProject-Inc/sinpro-dev#343]
# Tasks

- [x] `npm version minor or npm version patch で package のバージョンを 3 箇所書き換える。`を以下に書き換える
```
マイナーバージョンを上げる場合 `npm version minor` を実行する。パッチバージョンを上げる場合 `npm version patch` を実行する。
```

- [x] `PR を作成する。その際、Issue は Close しないので書き換えなくていい。`を以下に書き換える
```
PR を作成する。PR title は `<Issue Title> <Issue Number>` とする。コメントの記載やチェックボックスは変更しないこと。
```

- [x] `PR は、何もチェックせずにマージする。`を以下に書き換える
```
PDMに連絡し、PRをマージしてもらう。
```

- [x] 「Server」セクションで、ssh dev@sinpro-dev コマンド以外のコマンドも強調タグで囲む

- [x] 「告知」セクションの Docs更新アナウンスのテンプレートを以下に変更する。
```
@channel

sinpro-dev Docs を更新しましたのでご案内いたします。

[docs 更新履歴](https://github.com/sinProject-Inc/sinpro-dev/commits/main/docs) を確認し、202x 年 x 月 x 日のコミット以降で、興味があるところ、業務に関係するところを確認しておいてくださいませ。

確認が完了しましたらリアクションをお願い致します。
また、気になることがありましたらお気軽にご連絡くださいませ。
よろしくお願いいたします。

@岩崎 真也 さん、SNS 告知お願い致します。
```

- [x] `ドキュメントの追加や更新があれば、 #give-and-take でアナウンスする。` の下に以下のチェックボックスを追加する。
```
Docs更新アナウンスのテンプレートの「202x 年 x 月 x 日」は、前回リリース日の翌日の日付を入れる。 
```

- [x] `SNSで告知するよう、プロダクトマネージャーに依頼する`を削除する。

- [x] `ドキュメントの追加や更新があれば、 #give-and-take でアナウンスする。`を以下に変更する。
```
ドキュメントの追加や更新があれば、 以下のテンプレートを使用しアナウンスをする。
```

Estimated Time: 10min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
