### ISSUE TITLE
Release v0.73.0

### ISSUE THREAD

**Issue by Acha0203** [sinProject-Inc/sinpro-dev#353]
# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Tasks

## Tasks

- [x] マイナーバージョンを上げる場合 `npm version minor` を実行する。パッチバージョンを上げる場合 `npm version patch` を実行する。
- [x] push する。
- [x] PR を作成する。PR title は `<Issue Title> <Issue Number>` とする。その他 PR の記載やチェックボックスは変更しないこと。
- [x] PDMに連絡し、PRをマージしてもらう。
- [x] 作成された タグを origin に push する。

## GitHub

- [x] [Close されている PR 一覧](https://github.com/sinProject-Inc/sinpro-dev/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed) で、機能拡張だと思われるものに `enhancement` のラベルを付ける。
- [x] [GitHub のリリース 作成ページ](https://github.com/sinProject-Inc/sinpro-dev/releases)を開き、`Draft a new release` ボタンをクリックする。
- [x] `Choose a tag` で、新規作成したタグを選択する。
- [x] `Generate release notes` ボタンを押す。
- [x] 自動生成されたリリースノートの Release に関する項目を削除する。
- [x] Preview して問題がないかを確認する。
- [x] 問題なければ、`Publish release` ボタンを押してリリースを作成する。

## Server

- [x] `ssh dev@sinpro-dev` で接続する。
- [x] `cd ~/dev/sinpro-dev`
- [x] `git checkout main && git pull`
- [x] `npm i --legacy-peer-deps`
- [x] `npm run build`
- [x] `pm2 restart sinpro-dev`

## Check

- [x] サーバーの表示確認を行う

## 告知

- [x] ドキュメントの追加や更新があれば、 以下のテンプレートを使用しアナウンスをする。
- [x] Docs更新アナウンスのテンプレートの「202x 年 x 月 x 日」は、前回リリース日の翌日の日付を入れる。

```markdown
@channel

sinpro-dev Docs を更新しましたのでご案内いたします。

[docs 更新履歴](https://github.com/sinProject-Inc/sinpro-dev/commits/main/docs) を確認し、202x 年 x 月 x 日のコミット以降で、興味があるところ、業務に関係するところを確認しておいてくださいませ。

確認が完了しましたらリアクションをお願い致します。
また、気になることがありましたらお気軽にご連絡くださいませ。
よろしくお願いいたします。

@岩崎 真也 さん、SNS 告知お願い致します。
```
