### ISSUE TITLE
Replace M2 Pro to M3 Pro on Equipment and Supplies page

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#368]
# Tasks

リンクURLを準備します。
納期は年明けに決めましょう。

## 方針

Amazon アフィリエイトのリンクは画像リンクができなくなりました。よって、テキストリンクのみにします。
画像リンクの際は、レスポンシブにレイアウトを変更していましたが、テキストリンクでは不要です。

ただ、テキストリンクだけだと寂しいので、今後は、「なぜその商品をおすすめするのか」というコメントを入れたいと思っています。

- [ ] Replace M2 Pro to M3 Pro on Equipment and Supplies page

## URL
https://amzn.to/48yWZ0F

## Text
Apple 2023 MacBook Pro 11 コアCPU、14 コアGPU のM3 Proチップ搭載ノートパ ソコン:14.2 インチ Liquid Retina XDR ディスプレイ、18GB ユニファイドメモリ、 512GBの SSD ストレージ、iPhone や iPad との連係機能 - シルバー

## html
```html
<a href="https://amzn.to/48yWZ0F" target="_blank">Apple 2023 MacBook Pro 11 コアCPU、14 コアGPU のM3 Proチップ搭載ノートパ ソコン:14.2 インチ Liquid Retina XDR ディスプレイ、18GB ユニファイドメモリ、 512GBの SSD ストレージ、iPhone や iPad との連係機能 - シルバー</a>
```

## コメント

別イシューで対応する予定。

Estimated Time: 30min

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
