### ISSUE TITLE
Recruit

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#379]
# Tasks

## 社員紹介
- [ ] ネットワーク監視
- [ ] Javaエンジニア
- [ ] Python エンジニア
- [ ] PHPエンジニア

## 社内
- [ ] TypeScript
- [ ] C# ASP.NET

Estimated Time: 120min

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
