### ISSUE TITLE
Update npm packages

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#382]
# Tasks

## minor update

- [x] ncu --target minor 
- [x] ncu --target minor -u
- [x] npm i
- [x] npm run dev
- [x] npm run build

## major update

- [x] loop
  - [x] ncu
  - [x] ncu -u <package_name>
  - [x] npm i
  - [x] npm run dev
  - [x] npm run build

## important major update (svelte, vite)

- [x] loop
  - [x] ncu
  - [x] ncu -u <package_name>
  - [x] npm i
  - [x] npm run dev
  - [x] npm run build
  - [x] npm run check
  - [x] npm run typecheck

Estimated Time: 60min

# Writing the Issue

- [ ] Write each task for this issue using checkboxes
- [ ] Write all verbal instructions as tasks
- [ ] Add labels and assignees

# Before Working on the Issue

- [ ] Assign yourself
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
