### ISSUE TITLE
Update the wording in the GitHub Repository Settings

### ISSUE THREAD

**Issue by yoshimoto-takeshi** [sinProject-Inc/sinpro-dev#56]
# Tasks

- [x] GitHub Repository Settings の文言修正
- [x] Automatically delete head branches: Check の場所が違う
- [x] 場所 Pull Requests

500pt

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
