### ISSUE TITLE
Make it possible to press the PUSH MENU BUTTON

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#86]
# Tasks

- [x] Docsのページと同じ仕様にし、トップページにおいても、どのリンクをおしてもサウンドが鳴るようにする。 Play sound on click
- [x] PUSH MENU BUTTON をリンクにする。ジャンプ先は /docs
- [x] ホバー時はヘッダーと同じく青色。

期限：2023-07-28
3,000pt

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by anubhav1206** [comment]
Can I work on this?
