### ISSUE TITLE
Write issue titles in affirmative form

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-dev#91]
# Tasks

- [x] 「GitHub Issue - Title」の Example コードの下に、`Write issue titles in affirmative form, following the format.` を追加する
- [x] 以下を、Bad と Good としてサンプルを掲載する

Bad
Docs: Mobile sidebar button does not show when first navigating

Good
Docs: Display icons when first navigating on mobile devices

希望納期: 2023-07-26
希望料金: 500

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
